force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Buildings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Discharge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/populateMatchingUnitLookupValues.cls
global with sharing class populateMatchingUnitLookupValues implements Callable {
	global Object call(String action, Map<String, Object> args)
   {
       system.debug('######'+action);
       switch on action {
           when 'SelectOptions' {
               return SelectOptions((Map<String, Object>)args.get('input'), (Map<String, Object>)args.get('output'));
           }
       }
       return null;
    }
   
    private List<Map<String, Object>> SelectOptions(Map<String, Object> inputMap, Map<String, Object> outMap)
    {
       
        //String formatedselectedUnits;
        List<Id>selectedUitLst = new List<Id>();
         List<Map<String, Object>> optionList = new List<Map<String, Object>>();
          String Query = ' Select Id, Name from Unit__c WHERE Status__c=\'Vacant\'';
        if(inputMap.containsKey('BuildingId')){
            String buildingId = (String)inputMap.get('BuildingId');
            Query+= ' AND  Building__c=:buildingId';
           Map<String,Object>unitAssignemntMap = (Map<String,Object>)inputMap.get('UnitAssignment');
            if(unitAssignemntMap.containsKey('selectedUnits') ){
                String  selectedUnits = (String)unitAssignemntMap.get('selectedUnits');
                if(String.isNotBlank(selectedUnits) && selectedUnits!='null,' ){
                      system.debug('22232'+selectedUnits);
                selectedUitLst.addAll(selectedUnits.removeEnd(',').split(','));
                 system.debug('AAAA'+selectedUitLst);
                    Query+='AND Id Not IN:selectedUitLst';
                }
               
                
            }
          
           system.debug('QRY'+query); 
        for (Unit__c unitObj : database.query(Query))
        {
             Map<String, Object> option = new Map<String, Object>();
             option.put('name', unitObj.Id);
             option.put('value', unitObj.Name);
             optionList.add(option);
        }
        
        outMap.put('options', optionList);
        }
       
                
        return optionList;
    }
}